name: Go Test CI

on:
  push:
    branches:
      - testing 
  pull_request:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23' 

    - name: Change directory to specific folder
      working-directory: . 
      run: echo "Switched to specific directory"

    - name: Install dependencies
      working-directory: . 
      run: go mod tidy

    - name: Run tests
      working-directory: .
      run: go test ./...
